(() => { const D='../data/'; const S={layer:'rain',base:'1991',rows:[],countries:[],history:{},map:null,groups:[],selected:null,chart:null};
const $=id=>document.getElementById(id), cn={Indonesia:'印度尼西亚',Malaysia:'马来西亚'};
const esc=s=>String(s??'—').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m])); const pct=v=>v==null?'缺测':`${v.toFixed(1)}%`; const mm=v=>v==null?'缺测':`${v.toFixed(1)} mm`;
const get=async f=>{const r=await fetch(D+f);if(!r.ok)throw Error(f);return r.json()};
const value=r=>{if(S.layer==='rain')return r.rain_30d_mm;if(S.layer==='anom')return S.base==='1991'?r.rain_30d_ratio_1991_2020:r.rain_30d_ratio_recent5y;if(S.layer==='extreme')return r.extreme_rain_days_30d;if(S.layer==='dry')return r.current_dry_spell_days;return S.layer==='f7'?r.forecast_rain_1_7d_mm:r.forecast_rain_8_15d_mm};
const color=r=>{let v=value(r);if(v==null)return'#cbd5d2';if(S.layer==='rain')return v<=20?'#8c2d24':v<=50?'#c85b49':v<=100?'#e89b65':v<=150?'#f0d690':v<=200?'#d9e29b':v<=300?'#9dd3a3':v<=400?'#59b99b':v<=500?'#258c83':'#09655f';if(S.layer==='anom')return v<=30?'#8c2d24':v<=50?'#d6604d':v<=84?'#f3c786':v<=115?'#e8ead5':v<=150?'#9bd6c9':v<=200?'#4da99b':'#087d73';if(S.layer==='extreme')return v===0?'#e8ead5':v===1?'#f3c786':v===2?'#d6604d':'#8c2d24';if(S.layer==='dry')return v===0?'#e8ead5':v<=5?'#d6e4a8':v<=10?'#f3d187':v<=20?'#e59a59':v<=30?'#d6604d':'#8c2d24';return v<=10?'#f3e7ba':v<=30?'#b6d9b8':v<=60?'#75c5ae':v<=100?'#37a48d':'#087d73'};
const name=f=>f.properties.shapeName||f.properties.NAME_1||f.properties.name||f.properties.Name||''; const norm=s=>String(s).toLowerCase().replace(/[^a-z0-9]/g,'');
function row(country,f){let n=norm(name(f));return S.rows.find(r=>r.country===country&&((norm(r.weather_region_id).includes(n)||n.includes(norm(r.weather_region_id)))||(norm(r.region).includes(n)||n.includes(norm(r.region)))))}
function style(r,c){let sel=r&&S.selected?.weather_region_id===r.weather_region_id;return{color:sel?'#172c3a':c==='Indonesia'?'#0b655c':'#455c78',weight:sel?4:c==='Indonesia'?2.8:2.5,fillColor:r?color(r):'#dce7e5',fillOpacity:r?.65:.2,dashArray:r?null:'4 4'}}
function updateMap(){S.groups.forEach(g=>g.eachLayer(l=>l.setStyle(style(l._row,l._country))));legend()}
function legend(){let text=S.layer==='rain'?'30日累计降雨（mm）':S.layer==='anom'?`30日降雨距平（${S.base==='1991'?'1991—2020':'近五年'}）`:S.layer==='extreme'?'近30日 >150mm/天次数':S.layer==='dry'?'当前连续无雨日':'预报累计降雨（mm）';$('legend').innerHTML=`<b>${text}</b><br><i style="background:#8c2d24"></i>偏低/高风险　<i style="background:#e8ead5"></i>中性　<i style="background:#087d73"></i>偏高/补水<br><small>深青国界：印度尼西亚　蓝灰国界：马来西亚</small>`}
function detail(r){S.selected=r;updateMap();$('chartTitle').textContent=`${r.region}｜降雨趋势`;$('detail').innerHTML=`<h2>${esc(r.region)}</h2><p>${cn[r.country]} · 占本国产量 ${pct((r.production_share_country||0)*100)} · 占东南亚产量 ${pct((r.production_share_se_asia||0)*100)}</p><h3>当前降雨实况</h3>${kv('观测截至',r.date_end)}${kv('30日累计降雨',mm(r.rain_30d_mm))}${kv('分类',r.rain_30d_class)}${kv('相对1991—2020',pct(r.rain_30d_ratio_1991_2020))}${kv('相对近五年',pct(r.rain_30d_ratio_recent5y))}${kv('当前连续无雨',r.current_dry_spell_days==null?'缺测':r.current_dry_spell_days+' 天')}${kv('30日最长连续无雨',r.max_dry_spell_30d==null?'缺测':r.max_dry_spell_30d+' 天')}${kv('极端降雨次数',r.extreme_rain_days_30d==null?'缺测':r.extreme_rain_days_30d+' 次')}${kv('最大单日降雨',`${mm(r.max_daily_rain_30d)}｜${r.max_daily_rain_date||'—'}`)}<h3>未来降雨</h3>${kv('未来1—7日',mm(r.forecast_rain_1_7d_mm))}${kv('未来8—15日',mm(r.forecast_rain_8_15d_mm))}${kv('未来变化',r.forecast_change_class)}${kv('预报',r.forecast_model)}<h3>判断</h3><p>当前事实：${r.rain_30d_mm<=100?'进入低降雨区，棕榈生长可能受到限制。':'30日降雨未进入低降雨区。'}</p><p>异常证据：${S.base==='1991'?pct(r.rain_30d_ratio_1991_2020):pct(r.rain_30d_ratio_recent5y)}。</p><p>未来变化：${r.forecast_change_class}；降雨预报不能单独确认水分压力已解除。</p><p>尚不能确认：植物可利用水和P−ET0尚未接入。</p>`; chart(r)}
const kv=(a,b)=>`<div class="kv"><span>${a}</span><b>${esc(b)}</b></div>`;
function chart(r){let h=S.history[r.weather_region_id]||[];let labels=h.map(x=>x.date.slice(5));let vals=h.map(x=>x.precipitation_mm);if(S.chart)S.chart.destroy();S.chart=new Chart($('chart'),{type:'bar',data:{labels,datasets:[{label:'逐日降雨（mm）',data:vals,backgroundColor:'#258c83'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true}}}})}
function countries(){let html=S.countries.map(c=>`<article data-country="${c.country}"><b>${cn[c.country]}</b><p>30日加权降雨：${mm(c.rain_30d_weighted_mm)}<br>低降雨区：${pct(c.low_rain_share_country)} 本国产量<br>低于正常区：${pct(c.below_normal_share_country)} 本国产量<br>覆盖率：${pct(c.coverage)}</p></article>`).join('');$('countries').innerHTML=html;document.querySelectorAll('[data-country]').forEach(x=>x.onclick=()=>{let g=S.groups.find(q=>q._country===x.dataset.country);if(g)S.map.fitBounds(g.getBounds().pad(.1))})}
function summaries(){let total=S.rows.reduce((a,r)=>a+(r.production_tonnes||0),0),share=fn=>S.rows.reduce((a,r)=>a+(fn(r)?r.production_tonnes||0:0),0)/total*100;$('metrics').innerHTML=[['低降雨区',share(r=>r.rain_30d_mm!=null&&r.rain_30d_mm<=100)],['低于正常区',share(r=>r.rain_30d_ratio_1991_2020!=null&&r.rain_30d_ratio_1991_2020<=84)],['连续无雨（中等以上）',share(r=>(r.current_dry_spell_days||0)>=11)],['极端降雨影响',share(r=>(r.extreme_rain_days_30d||0)>0)],['未来可能改善',share(r=>r.forecast_change_class==='可能改善')],['未来继续转差',share(r=>r.forecast_change_class==='继续转差')]].map(x=>`<article class="card"><span>${x[0]}</span><strong>${pct(x[1])}</strong><small>占东南亚产量</small></article>`).join('');$('conclusion').textContent=`印尼和马来西亚共 ${S.rows.length} 个棕榈油产区纳入降雨监测；低降雨、距平、连续无雨和极端降雨均独立呈现，不据此直接判定减产。`;$('evidence').textContent='未来预报仅表达降雨条件可能改善或转差；植物可利用水与P−ET0待后续接入。'}
async function map(){S.map=L.map('map',{minZoom:3,maxZoom:9}).setView([1.5,108],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(S.map);for(const [country,file] of [['Indonesia','indonesia_admin1.geojson'],['Malaysia','malaysia_admin1.geojson']]){let geo=await get('admin1_geojson/'+file);let g=L.geoJSON(geo,{style:f=>style(row(country,f),country),onEachFeature:(f,l)=>{let r=row(country,f);l._row=r;l._country=country;l.bindTooltip(`<b>${esc(r?.region||name(f))}</b><br>${cn[country]}`,{sticky:true});l.on('click',()=>r&&detail(r))}}).addTo(S.map);g._country=country;S.groups.push(g)}let label=L.control({position:'topright'});label.onAdd=()=>{let d=L.DomUtil.create('div','country-label');d.innerHTML='印度尼西亚<br><br>马来西亚';return d};label.addTo(S.map);S.map.fitBounds(L.featureGroup(S.groups).getBounds().pad(.05));}
function tabs(){let ls=[['rain','30日累计降雨'],['anom','30日降雨距平'],['extreme','极端降雨'],['dry','连续无雨'],['f7','未来1—7日'],['f8','未来8—15日']];$('layers').innerHTML=ls.map(x=>`<button class="${x[0]==='rain'?'active':''}" data-layer="${x[0]}">${x[1]}</button>`).join('');document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{S.layer=b.dataset.layer;document.querySelectorAll('[data-layer]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-base]').forEach(x=>x.disabled=S.layer!=='anom');updateMap()});document.querySelectorAll('[data-base]').forEach(b=>b.onclick=()=>{S.base=b.dataset.base;document.querySelectorAll('[data-base]').forEach(x=>x.classList.toggle('active',x===b));updateMap()});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{let is=b.dataset.tab==='rain';$('rainWorkspace').classList.toggle('hidden',!is);$('placeholder').classList.toggle('hidden',is);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));if(!is)$('placeholder').innerHTML=`<h2>${b.textContent}</h2><p>建设中。${b.dataset.tab==='heat'?'高温不能作为孤立的棕榈油供应风险指标，后续将结合VPD、降雨和根区土壤水分判断。':'后续将接入有效降雨、ET0/PET、P−ET0、植物可利用水与径流等经过验证的数据。'}</p>`});document.querySelectorAll('[data-primary]').forEach(b=>b.onclick=()=>{let climate=b.dataset.primary==='climate';$('palmContent').classList.toggle('hidden',climate);$('climate').classList.toggle('hidden',!climate);document.querySelectorAll('[data-primary]').forEach(x=>x.classList.toggle('active',x===b))})}
async function init(){try{let [rows,countries,history,meta]=await Promise.all([get('palm_rain_region_latest.json'),get('palm_rain_country_latest.json'),get('palm_rain_history_90d.json'),get('palm_rain_meta.json')]);S.rows=rows;S.countries=countries;S.history=history;$('status').textContent=`观测截止：${rows[0]?.date_end||'—'} ｜ 预报：${meta.forecast_source} ｜ 版本：${meta.version}`;$('method').textContent=`日降雨：${meta.daily_source}；30日窗口：${meta.window}；无雨日：${meta.dry_day_definition}；极端降雨：${meta.extreme_rain_definition}；近五年：${meta.recent5_years.join('—')}；${meta.forecast_note}`;tabs();summaries();countries();await map();let first=[...rows].sort((a,b)=>((a.rain_30d_mm<=100?0:1)-(b.rain_30d_mm<=100?0:1))||((b.production_tonnes||0)-(a.production_tonnes||0)))[0];detail(first)}catch(e){console.error(e);$('status').textContent='数据加载失败：请检查专题数据文件。'}}init();})();
